# Generated by Django 2.2.8 on 2020-05-16 21:08

import WebApp.models
import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duedate', models.DateTimeField(default=datetime.datetime(2020, 5, 16, 17, 8, 2, 390940))),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('student_list', djongo.models.fields.ArrayField(model_container=WebApp.models.AttendanceEntry)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discord_name', models.CharField(max_length=100)),
                ('presence', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discord_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('students', djongo.models.fields.ArrayField(model_container=WebApp.models.Student)),
                ('assignments', djongo.models.fields.ArrayField(model_container=WebApp.models.Assignment)),
                ('filter_words', djongo.models.fields.ArrayField(model_container=WebApp.models.StringField)),
                ('attendance', djongo.models.fields.ArrayField(model_container=WebApp.models.Attendance)),
                ('reminders', djongo.models.fields.ArrayField(model_container=WebApp.models.Reminder)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 5, 16, 17, 8, 2, 391937))),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='StringField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 5, 16, 17, 8, 2, 391937))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discord_name', models.CharField(max_length=100)),
            ],
        ),
    ]
