# Generated by Django 2.2.8 on 2020-05-16 03:45

import WebApp.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', djongo.models.fields.EmbeddedField(model_container=WebApp.models.Student, model_form_class=WebApp.models.StudentForm, null=True)),
                ('students', djongo.models.fields.ArrayField(model_container=WebApp.models.Student, model_form_class=WebApp.models.StudentForm)),
                ('assignments', djongo.models.fields.ArrayField(model_container=WebApp.models.Assignment, model_form_class=WebApp.models.AssignmentForm)),
            ],
        ),
        migrations.DeleteModel(
            name='StringField',
        ),
    ]
