# Generated by Django 2.2.8 on 2020-05-17 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20200516_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='duedate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 4, 9, 22, 249355)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 4, 9, 22, 251348)),
        ),
        migrations.AlterField(
            model_name='stringfield',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 4, 9, 22, 250352)),
        ),
    ]
